### ISSUE TITLE
Error on call floating.enable on AppLifecycleState.hidden

### ISSUE THREAD

**Issue by st3hz3r** [wrbl606/floating#19]
Hi.
When I try to call floating.enable() on lifecycleState == AppLifecycleState.hidden, it throws an exception "Activity must be resumed to enter picture-in-picture". It works almost well on AppLifecycleState.incative, but the issue is triggering floating.enable() even if Quick Settings panel is shown. Any ideas how to use it exactly on hidden?

**Comment by FranciscoVenegas** [comment]
Yea, I have the same problem.
When I show the Quick Settings Panel on my app runnig in Flutter 3.13 (and 3.22 too), the app changes to AppLifecycleState.incative, but my app is not changing to minimize. 
And also, you only can call  floating.enable() when the app is in AppLifecycleState.incative or AppLifecycleState.resume.
This did not happen in version 3.10.6. But soon I will have to update.

**Comment by wrbl606** [comment]
Took a while, but will be available in 3.0.0 via `.enable(AutoEnable());`.

**Comment by FranciscoVenegas** [comment]
AutoEnable does avoid the problem between the 'inactive' state and showing Quick Settings for Android versions that support automatic mode (SDK 31+). Unfortunately, for Android versions that do not support this mode (SDK's less than 31), they will have to call the manual PiP function in the inactive state.

The problem is the new AppLifeCycle, since the 'inactive' state is activated when the Quick Settings are displayed on Android, changing to PiP mode without the action of 'minimizing' the app.

Just to finish, I understand that this is a change made by the Flutter team and not a Floating Plugin issue, but any information on this would be appreciated.

**Comment by kmartins** [comment]
@FranciscoVenegas Do you found a solution?
